CREATE TABLE IF NOT EXISTS users (
                                     ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     Name VARCHAR(255) NOT NULL,
                                     Email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (ID),
                                     CONSTRAINT uq_user_email UNIQUE (Email)
);

CREATE TABLE IF NOT EXISTS items (
                                     ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     Name VARCHAR(255) NOT NULL,
                                     Description VARCHAR(512) NOT NULL,
                                     IsAvailable BOOLEAN,
                                     OwnerID BIGINT NOT NULL,
                                     RequestID BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY(id),
                                     CONSTRAINT fk_item_user FOREIGN KEY(OwnerId) REFERENCES users(ID)
);